### ISSUE TITLE
add Quick sort 

### ISSUE THREAD

**Issue by Sofiyan-coder** [panditakshay402/HACKTOBERFEST_2024#1]

**Comment by Sofiyan-coder** [comment]
Hi @panditakshay402 , could you please assign this issue to me? I'd love to contribute and start my open-source journey with this project!

**Comment by dauntless05** [comment]
hi please assign me this issue!!

**Comment by panditakshay402** [comment]
@Sofiyan-coder @dauntless05  you can directly commit and send PR.
Before this kindly follow the **rules** from  readme.md file to get PR accepted.
