### ISSUE TITLE
Painter's Partition Problem

### ISSUE THREAD

**Issue by panditakshay402** [panditakshay402/HACKTOBERFEST_2024#32]
Kindly follow all the rules from readme.md to get PR merged

**Comment by panditakshay402** [comment]
@Salonisaroha

**Comment by karanghuge01** [comment]
I want to add Painter's Partition Problem" problem. kindly assign this issue to me.

**Comment by karanghuge01** [comment]
on hacktoberfest showing me Repository Excluded
