### ISSUE TITLE
add Binary search

### ISSUE THREAD

**Issue by Sofiyan-coder** [panditakshay402/HACKTOBERFEST_2024#4]
Hi @panditakshay402 , could you please assign this issue to me? I'd love to contribute and start my open-source journey with this project!

**Comment by dauntless05** [comment]
hi please assign me this issue!!

**Comment by Aneeshhhhh** [comment]
Hii, could you please assign this issue to me?

**Comment by panditakshay402** [comment]
> Hii, could you please assign this issue to me?

@Aneeshhhhh you can start without assigning
