### ISSUE TITLE
add Linear Search

### ISSUE THREAD

**Issue by Sofiyan-coder** [panditakshay402/HACKTOBERFEST_2024#7]
Hi @panditakshay402 , could you please assign this issue to me? I'd love to contribute and start my open-source journey with this project!

**Comment by dauntless05** [comment]
hi please assign me this issue!!

**Comment by panditakshay402** [comment]
@Sofiyan-coder @dauntless05 you can directly commit and send PR.
Before this kindly follow the rules from readme.md file to get PR accepted.

**Comment by dauntless05** [comment]
@panditakshay402 its giving permission denied error.

**Comment by panditakshay402** [comment]
> @panditakshay402 its giving permission denied error.
> 

Read Readme.md file properly specially How to contribute follow steps.

**Comment by Sofiyan-coder** [comment]
@panditakshay402 would you please add HACKTOBERFEST 2024 labels to all issues it will confirm the issues are valid

**Comment by panditakshay402** [comment]
@Sofiyan-coder sure
